# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 308cc1c421f972ce978605130c2f2acead914e97243662d65156b87b00744a41eb9c767cbb307e0a3b58ab012134d560bd467f41c12616eb43648e438eebdb6d

test:
  secret_key_base: c835cf78db345f999227f8c94e1660a20f6f086b5d646a62405a459be88a258a327ac4f49bbcb5aa07ab4ef4ac3dd8dba938f45e049ef8049a7357b4c945a6be

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
